version: "3.8"
services:
  redis:
    image: redis:latest
    container_name: redis-container
    command: redis-server --save 60 1 --loglevel warning
    ports:
      - "6379:6379"
    env_file:
      - .env.redis
    volumes:
      - ./redis_data:/data


