services:
  redis:
    image: redis:latest
    container_name: redis-container
    command: redis-server --save 60 1 --loglevel warning
    ports:
      - "6379:6379"
    env_file:
      - .env.redis
    volumes:
      - ./redis_data:/data

  backend:
    depends_on:
      - redis
    build: .
    restart: unless-stopped
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      # Mount SSL certificate from host to container
      - ./ssl/rds/us-east-1-bundle.pem:/app/ssl/rds/us-east-1-bundle.pem:ro
      # mount node_modules as anonymous volume so host files don’t overwrite container deps
      - /app/node_modules




